language: ruby
rvm:
  - 2.2
bundler_args: ""
script:
 - ./bin/jekyll build
 - ./bin/publish
 - rm -R ./_site
 - ./bin/jekyll contentful
 - ./bin/jekyll build --config _config.staging.yml
 - ./bin/s3_website push
notifications:
  slack:
    on_success: always
